apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terraforms.tf.isaaguilar.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: tf.isaaguilar.com
  names:
    kind: Terraform
    listKind: TerraformList
    plural: terraforms
    singular: terraform
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Terraform is the Schema for the terraforms API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TerraformSpec defines the desired state of Terraform
          properties:
            config:
              description: TerraformConfig points to the tfvars to deploy against
                the stack
              properties:
                applyOnCreate:
                  description: ApplyOnCreate is used to apply any planned changes
                    when the resource is first created. Omitting this or setting it
                    to false will resort to on demand apply.
                  type: boolean
                applyOnUpdate:
                  description: ApplyOnUpdate is used to apply any planned changes
                    when the resource is updated. Omitting this or setting it to false
                    will resort to on demand apply.
                  type: boolean
                cloudProfile:
                  description: CloudProfile defines the selector to cloud access keys
                    or roles to attach to the terraform job executor. If it begines
                    with "kiam-", the controller will assume this is a role and add
                    the kiam annotation. Other clouds may have different role based
                    mechanisms so other prefixes would need to be hard coded in the
                    controller's if statements later. The default behaviour is to
                    load the CloudProfile from a secret as environment vars.
                  type: string
                env:
                  items:
                    description: EnvVar defines key/value pairs of env vars that get
                      picked up by terraform
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
                reconcile:
                  description: Reconcile are the settings used for auto-reconciliation
                  properties:
                    enable:
                      description: Enable used to turn on the auto reconciliation
                        of tfstate to actual provisions. Default to false
                      type: boolean
                    syncPeriod:
                      description: SyncPeriod can be used to set a custom time to
                        check actual provisions to tfstate. Defaults to 60 minutes
                      format: int64
                      type: integer
                  required:
                  - enable
                  type: object
                sources:
                  items:
                    description: SrcOpts defines a terraform source location (eg git::SSH
                      or git::HTTPS)
                    properties:
                      address:
                        description: Address defines the source address of the tf
                          resources. This this var will try to accept any format defined
                          in https://www.terraform.io/docs/modules/sources.html When
                          downloading `tfvars`, the double slash `//` syntax is used
                          to define dir or tfvar files. This can be used multiple
                          times for multiple items.
                        type: string
                    required:
                    - address
                    type: object
                  type: array
              type: object
            sshKeySecretRefs:
              items:
                description: SSHKeySecretRef defines the secret where the SSH key
                  (for the proxy, git, etc) is stored
                properties:
                  key:
                    description: Key in the secret ref. Default to `id_rsa`
                    type: string
                  name:
                    description: Name the secret name that has the SSH key
                    type: string
                  namespace:
                    description: Namespace of the secret; Default is the namespace
                      of the terraform resource
                    type: string
                required:
                - name
                type: object
              type: array
            sshProxy:
              description: TODO refactor to SSHTunnel
              properties:
                host:
                  type: string
                sshKeySecretRef:
                  description: SSHKeySecretRef defines the secret where the SSH key
                    (for the proxy, git, etc) is stored
                  properties:
                    key:
                      description: Key in the secret ref. Default to `id_rsa`
                      type: string
                    name:
                      description: Name the secret name that has the SSH key
                      type: string
                    namespace:
                      description: Namespace of the secret; Default is the namespace
                        of the terraform resource
                      type: string
                  required:
                  - name
                  type: object
                user:
                  type: string
              required:
              - sshKeySecretRef
              type: object
            stack:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                configMap:
                  type: string
                source:
                  description: SrcOpts defines a terraform source location (eg git::SSH
                    or git::HTTPS)
                  properties:
                    address:
                      description: Address defines the source address of the tf resources.
                        This this var will try to accept any format defined in https://www.terraform.io/docs/modules/sources.html
                        When downloading `tfvars`, the double slash `//` syntax is
                        used to define dir or tfvar files. This can be used multiple
                        times for multiple items.
                      type: string
                  required:
                  - address
                  type: object
              type: object
            tokenSecretRefs:
              items:
                description: TokenSecetRef defines the token or password that can
                  be used to log into a system (eg git)
                properties:
                  key:
                    description: Key in the secret ref. Default to `token`
                    type: string
                  name:
                    description: Name the secret name that has the token or password
                    type: string
                  namespace:
                    description: Namespace of the secret; Default is the namespace
                      of the terraform resource
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - config
          - stack
          type: object
        status:
          description: TerraformStatus defines the observed state of Terraform
          properties:
            lastGeneration:
              format: int64
              type: integer
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - lastGeneration
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
