apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terraforms.tf.isaaguilar.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: tf.isaaguilar.com
  names:
    kind: Terraform
    listKind: TerraformList
    plural: terraforms
    singular: terraform
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            auth:
              properties:
                key:
                  type: string
                name:
                  type: string
                type:
                  description: Type is either 'key' or 'password' or omit to skip
                    creds
                  type: string
              required:
              - type
              - key
              - name
              type: object
            config:
              properties:
                env:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
                sources:
                  items:
                    properties:
                      address:
                        description: Address defines the source address of the tf
                          resources. This this var will try to accept any format defined
                          in https://www.terraform.io/docs/modules/sources.html When
                          downloading `tfvars`, the double slash `//` syntax is used
                          to define dir or tfvar files. This can be used multiple
                          times for multiple items.
                        type: string
                      auth:
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                          type:
                            description: Type is either 'key' or 'password' or omit
                              to skip creds
                            type: string
                        required:
                        - type
                        - key
                        - name
                        type: object
                      extras:
                        items:
                          type: string
                        type: array
                      sshProxy:
                        description: SSHProxy can be defined for each source, or omit
                          this to use global
                        properties:
                          auth:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                              type:
                                description: Type is either 'key' or 'password' or
                                  omit to skip creds
                                type: string
                            required:
                            - type
                            - key
                            - name
                            type: object
                          host:
                            description: Auth   string  `json:"auth,omitempty"`
                            type: string
                          user:
                            type: string
                        type: object
                    required:
                    - address
                    type: object
                  type: array
              type: object
            sshProxy:
              properties:
                auth:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                    type:
                      description: Type is either 'key' or 'password' or omit to skip
                        creds
                      type: string
                  required:
                  - type
                  - key
                  - name
                  type: object
                host:
                  description: Auth   string  `json:"auth,omitempty"`
                  type: string
                user:
                  type: string
              type: object
            stack:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                configMap:
                  type: string
                source:
                  properties:
                    address:
                      description: Address defines the source address of the tf resources.
                        This this var will try to accept any format defined in https://www.terraform.io/docs/modules/sources.html
                        When downloading `tfvars`, the double slash `//` syntax is
                        used to define dir or tfvar files. This can be used multiple
                        times for multiple items.
                      type: string
                    auth:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        type:
                          description: Type is either 'key' or 'password' or omit
                            to skip creds
                          type: string
                      required:
                      - type
                      - key
                      - name
                      type: object
                    extras:
                      items:
                        type: string
                      type: array
                    sshProxy:
                      description: SSHProxy can be defined for each source, or omit
                        this to use global
                      properties:
                        auth:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            type:
                              description: Type is either 'key' or 'password' or omit
                                to skip creds
                              type: string
                          required:
                          - type
                          - key
                          - name
                          type: object
                        host:
                          description: Auth   string  `json:"auth,omitempty"`
                          type: string
                        user:
                          type: string
                      type: object
                  required:
                  - address
                  type: object
              type: object
          required:
          - stack
          - config
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
