apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terraforms.tf.isaaguilar.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: tf.isaaguilar.com
  names:
    kind: Terraform
    listKind: TerraformList
    plural: terraforms
    singular: terraform
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                cloudProfile:
                  description: CloudProfile defines the selector to cloud access keys
                    or roles to attach to the terraform job executor. If it begines
                    with "kiam-", the controller will assume this is a role and add
                    the kiam annotation. Other clouds may have different role based
                    mechanisms so other prefixes would need to be hard coded in the
                    controller's if statements later. The default behaviour is to
                    load the CloudProfile from a secret as environment vars.
                  type: string
                env:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
                sources:
                  items:
                    properties:
                      address:
                        description: Address defines the source address of the tf
                          resources. This this var will try to accept any format defined
                          in https://www.terraform.io/docs/modules/sources.html When
                          downloading `tfvars`, the double slash `//` syntax is used
                          to define dir or tfvar files. This can be used multiple
                          times for multiple items.
                        type: string
                    required:
                    - address
                    type: object
                  type: array
              type: object
            sshKeySecretRefs:
              items:
                properties:
                  key:
                    description: Key in the secret ref. Default to `id_rsa`
                    type: string
                  name:
                    description: Name the secret name that has the SSH key
                    type: string
                  namespace:
                    description: Namespace of the secret; Default is the namespace
                      of the terraform resource
                    type: string
                required:
                - name
                type: object
              type: array
            sshProxy:
              description: TODO refactor to SSHTunnel
              properties:
                host:
                  type: string
                sshKeySecretRef:
                  properties:
                    key:
                      description: Key in the secret ref. Default to `id_rsa`
                      type: string
                    name:
                      description: Name the secret name that has the SSH key
                      type: string
                    namespace:
                      description: Namespace of the secret; Default is the namespace
                        of the terraform resource
                      type: string
                  required:
                  - name
                  type: object
                user:
                  type: string
              required:
              - sshKeySecretRef
              type: object
            stack:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                configMap:
                  type: string
                source:
                  properties:
                    address:
                      description: Address defines the source address of the tf resources.
                        This this var will try to accept any format defined in https://www.terraform.io/docs/modules/sources.html
                        When downloading `tfvars`, the double slash `//` syntax is
                        used to define dir or tfvar files. This can be used multiple
                        times for multiple items.
                      type: string
                  required:
                  - address
                  type: object
              type: object
            tokenSecretRefs:
              items:
                properties:
                  key:
                    description: Key in the secret ref. Default to `token`
                    type: string
                  name:
                    description: Name the secret name that has the token or password
                    type: string
                  namespace:
                    description: Namespace of the secret; Default is the namespace
                      of the terraform resource
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - stack
          - config
          type: object
        status:
          properties:
            lastGeneration:
              format: int64
              type: integer
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - phase
          - lastGeneration
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
