apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: postrun-script
spec:
  stack:
    terraformVersion: 0.12.23
    source:
      address: <tf-module-git-repo>
  config:
    ignoreDelete: true
    credentials:
    - secretNameRef:
       name: aws-session-credentials    

    # ----- Run a postrun script after terraform runs: -------

    # Make sure to include the shebang. To test scripts before running this in 
    # tf-operator, try pulling the terraform-execution pod's image 
    # > (eg isaaguilar/tfops:0.12.23). 
    #
    # You may have to install your own packages to run some commands. 
    # For example, this example uses awscli which is installed via pip. Pip 
    # also needs to be installed.
    postrunScript: |-
      #!/usr/bin/env bash
      echo "Saving output to S3"
      if [ -z `which pip` ];then 
        apk add --update-cache python python-dev py-pip build-base 
      fi
      if [ -z `which aws` ];then
        pip install awscli
      fi

      ### Let's pretend there is an output.txt that the tf module creates
      #
      aws s3 cp output.txt s3://my-terraform-bucket/output/output.txt
