apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: irsa-role-and-policy-example
  labels:
    type: irsa
spec:
  sshProxy:
    host: 10.0.0.200
    user: admin
    sshKeySecretRef:
      name: proxysshkey
  scmAuthMethods:
  - host: git.example.com
    git:
      ssh:
        requireProxy: true
        sshKeySecretRef:
          name: gitsshkey
  stack:
    source:
      address: git@git.example.com:cloudops/terraform.git//modules/irsa-role-and-policy
  config:
    terraformVersion: 0.12.23
    applyOnCreate: true
    applyOnUpdate: true
    applyOnDelete: true
    reconcile:
      enable: false
      syncPeriod: 60 # int in minutes
    cloudProfile: admin-cloud-credentials
    sources:
    - address: git@git.example.com:cloudops/tfvars.git//irsa-example
