apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: irsa-role-and-policy-example
  labels:
    type: irsa
spec:
  sshProxy:
    host: 10.0.0.200
    user: admin
    sshKeySecretRef:
      name: proxysshkey
  scmAuthMethods:
  - host: git.example.com
    git:
      ssh:
        requireProxy: true
        sshKeySecretRef:
          name: gitsshkey
  stack:
    terraformVersion: 0.12.23
    source:
      address: git@github.com:isaaguilar/my-tf-modules.git//stacks/irsa-role-and-policy
  config:
    customBackend: |-
      terraform {
        backend "s3" {
          key            = "tf-operator-example.tfstate"
          region         = "us-east-1"
          bucket         = "backend-terraform-isaaguilar"
          dynamodb_table = "backend-terraform-isaaguilar-lock"
          profile        = "default"
        }
      }
    applyOnCreate: false
    applyOnUpdate: false
    applyOnDelete: true
    reconcile:
      enable: false
      syncPeriod: 60 # int in minutes
    cloudProfile: admin-cloud-credentials
    sources:
    - address: git@git.example.com:cloudops/tfvars.git//irsa-example
