apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: public-ssh-git-repo
spec:
  scmAuthMethods:
  - host: github.com
    git:
      ssh:
        requireProxy: false
        sshKeySecretRef:
          name: git-sshkey-k8s-secret
          key: id_rsa
  stack:
    terraformVersion: 0.12.23
    source:
      address: git@github.com:isaaguilar/private-aws-tf-modules.git//s3-bucket
  config:
    ignoreDelete: true
    credentials:
    - secretNameRef:
       name: aws-session-credentials    
    env:
    - name: TF_VAR_name
      value: value      # fulfills the terraform module's "${var.name}"
