# Note:
# HTTPS repos for stacks are supported as long as they do not require a proxy.

apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: public-https-git-repo-protected
spec:
  scmAuthMethods:
  - host: github.com
    git:
      https:
        requireProxy: false
        tokenSecretRef:
          name: git-token-k8s-secret
          key: token
  
  terraformVersion: 0.12.23
  terraformModule:
    address: https://github.com/isaaguilar/private-aws-tf-modules.git//s3-bucket

  ignoreDelete: true
  credentials:
  - secretNameRef:
      name: aws-session-credentials    
  env:
  - name: TF_VAR_name
    value: value      # fulfills the terraform module's "${var.name}"
