apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: custom-backend
spec:

  terraformVersion: 0.12.23
  terraformModule:
    address: git@<tf-module-repo>.git

  ignoreDelete: true
  customBackend: |-
    terraform {
      backend "s3" {
        key            = "tf-operator/default/custom-backend.tfstate"
        region         = "us-east-1"
        bucket         = "example-terraform-bucket"
        dynamodb_table = "example-terraform-bucket-lock"
        profile        = "example-aws-profile"
      }
    }
  credentials:
  - secretNameRef:
      name: aws-session-credentials    
  env:
  - name: TF_VAR_name
    value: value      # fulfills the terraform module's "${var.name}"

